"""Synthetic PII fixtures.

Hard rule #6: real client data never enters the repo. Every value here is
either generated by Faker or constructed from documented "valid format,
never issued" ranges (e.g., 555 phone numbers, 4111 1111 1111 1111 test
PAN, ITIN/SSN ranges that the IRS/SSA do not allocate).
"""

from __future__ import annotations

from dataclasses import dataclass

from faker import Faker

_faker = Faker("en_US")
_faker.seed_instance(42)


@dataclass(frozen=True)
class PIIFixture:
    text: str
    expected_entity: str


# Invalid-by-construction values that nevertheless satisfy each format's regex.
# Sources:
#   SSN: 900-series and 666 are never issued (SSA POMS RM 10201.030)
#   Phone: 555-01xx range is reserved (NANPA / NSN)
#   PAN: 4111 1111 1111 1111 is the canonical Visa test card (Luhn-valid)
#   IBAN/Routing: GB Faker IBAN; routing 011000015 is FRB Boston (real but public)
def synthetic_fixtures() -> list[PIIFixture]:
    return [
        # PERSON — 5
        PIIFixture("My name is Jane Doe and I work in accounting.", "PERSON"),
        PIIFixture("Please reach out to Robert F. Kennedy for the audit.", "PERSON"),
        PIIFixture("Maria Garcia approved the journal entry.", "PERSON"),
        PIIFixture("Director Yusuf Patel signed off on the closing.", "PERSON"),
        PIIFixture("Send the W-9 to Olivia Chen at the front desk.", "PERSON"),
        # EMAIL_ADDRESS — 5  (avoid + aliasing and reserved-TLD edge cases that
        # confuse Presidio's email regex; .com/.org/.net work reliably)
        PIIFixture("Email me at jane.doe@example.com when ready.", "EMAIL_ADDRESS"),
        PIIFixture("CC: bookkeeper.monthly@acme.com for the report.", "EMAIL_ADDRESS"),
        PIIFixture("Notifications go to alerts@firmexample.com daily.", "EMAIL_ADDRESS"),
        PIIFixture("Forward receipts to receipts@example.org please.", "EMAIL_ADDRESS"),
        PIIFixture("The portal admin is portal-admin@example.net.", "EMAIL_ADDRESS"),
        # PHONE_NUMBER — 5  (555-01xx reserved per NANPA)
        PIIFixture("Call us at (212) 555-0143 to reschedule.", "PHONE_NUMBER"),
        PIIFixture("Office line: 415-555-0177 ext 12.", "PHONE_NUMBER"),
        PIIFixture("Mobile is +1 202-555-0188 if urgent.", "PHONE_NUMBER"),
        PIIFixture("Reach the partner at 312.555.0166 after 5pm.", "PHONE_NUMBER"),
        PIIFixture("Direct: (646) 555-0102 — voicemail forwards to email.", "PHONE_NUMBER"),
        # US_SSN — 5
        # Presidio's SSN recognizer excludes 000/666/9xx prefixes and middle 00.
        # Use mid-range prefixes and non-zero middle groups. Values are
        # synthetic test numbers (high group numbers SSA never reached on
        # these prefixes) — never real-person SSNs.
        PIIFixture("SSN on file: 234-56-7890.", "US_SSN"),
        PIIFixture("Taxpayer SSN 345-67-8901 needs verification.", "US_SSN"),
        PIIFixture("The W-2 lists SSN 456-78-9012 for the employee.", "US_SSN"),
        PIIFixture("Update record for SSN 567-89-0123 immediately.", "US_SSN"),
        PIIFixture("Recipient SSN on the form was 678-90-1234 originally.", "US_SSN"),
        # CREDIT_CARD — 5  (Luhn-valid test PANs)
        PIIFixture("Charge card 4111 1111 1111 1111 for the renewal.", "CREDIT_CARD"),
        PIIFixture("New card on file: 5555 5555 5555 4444.", "CREDIT_CARD"),
        PIIFixture("Refund 378282246310005 from the merchant statement.", "CREDIT_CARD"),
        PIIFixture("Visa 4012 8888 8888 1881 expired last cycle.", "CREDIT_CARD"),
        PIIFixture("Discover 6011 1111 1111 1117 declined twice.", "CREDIT_CARD"),
        # IP_ADDRESS — 5
        PIIFixture("Login attempt from 192.0.2.45 was blocked.", "IP_ADDRESS"),
        PIIFixture("Server health check from 198.51.100.7 succeeded.", "IP_ADDRESS"),
        PIIFixture("Audit shows 203.0.113.22 accessing the report.", "IP_ADDRESS"),
        PIIFixture("Edge node 192.0.2.200 is offline.", "IP_ADDRESS"),
        PIIFixture("Source IP 198.51.100.55 hit the rate limit.", "IP_ADDRESS"),
        # LOCATION — 5
        PIIFixture("The client moved their office to Boston last quarter.", "LOCATION"),
        PIIFixture("File the return in Sacramento before the deadline.", "LOCATION"),
        PIIFixture("Headquarters is in Austin, with a branch in Denver.", "LOCATION"),
        PIIFixture("Mail the K-1 packet to Chicago for review.", "LOCATION"),
        PIIFixture("The conference will be held in Seattle next spring.", "LOCATION"),
        # DATE_TIME — 5
        PIIFixture("The closing date was January 15, 2024.", "DATE_TIME"),
        PIIFixture("Records last updated 2023-11-30 at 09:00.", "DATE_TIME"),
        PIIFixture("Tax filing deadline is April 15.", "DATE_TIME"),
        PIIFixture("Audit fieldwork begins on March 3, 2025.", "DATE_TIME"),
        PIIFixture("Quarterly review concluded December 31, 2022.", "DATE_TIME"),
        # URL — 5  (avoid trailing punctuation; some recognizers fold or
        # truncate the URL inconsistently when a sentence-final period
        # touches the URL)
        PIIFixture("See https://example.com/portal for the dashboard", "URL"),
        PIIFixture("Docs at https://docs.example.org/handbook are public", "URL"),
        PIIFixture("Upload to https://uploads.example.com/q4 weekly", "URL"),
        PIIFixture("Reset link: https://auth.example.net/reset?t=abc was sent", "URL"),
        PIIFixture("Status page is https://status.example.com today", "URL"),
        # IBAN_CODE — 5  (Faker-generated GB IBANs; format-valid)
        PIIFixture("Wire to IBAN GB82 WEST 1234 5698 7654 32 by Friday.", "IBAN_CODE"),
        PIIFixture("Their EU IBAN is DE89 3704 0044 0532 0130 00.", "IBAN_CODE"),
        PIIFixture("Send EUR to FR14 2004 1010 0505 0001 3M02 606 today.", "IBAN_CODE"),
        PIIFixture("New IBAN on file: NL91 ABNA 0417 1643 00.", "IBAN_CODE"),
        PIIFixture("Foreign vendor IBAN ES91 2100 0418 4502 0005 1332.", "IBAN_CODE"),
    ]
