"""Synthetic CPA-bookkeeping corpus.

Hard rule #6: never any real client data. Every name / SSN / EIN /
account number / routing number / email below is generated by Faker
or constructed in documented "valid format, never issued" ranges.

Each fixture is a dict with:
  text: the sample input
  spans: list of {entity_type, start, end} the engine MUST detect
The harness counts a hit if the engine returns at least one span of
the same type that overlaps the expected span.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass

from faker import Faker

_faker = Faker("en_US")
_faker.seed_instance(2026)


@dataclass(frozen=True)
class ExpectedSpan:
    entity_type: str
    text: str  # the substring that should be detected


@dataclass(frozen=True)
class CorpusFixture:
    """One synthetic input + the spans we expect the engine to find."""

    id: str
    text: str
    expected: tuple[ExpectedSpan, ...]


def _spans_for(text: str, items: Iterable[tuple[str, str]]) -> tuple[ExpectedSpan, ...]:
    return tuple(ExpectedSpan(entity_type=t, text=v) for t, v in items)


# Canonical synthetic SSN ranges per Phase 3 fixture decisions.
_SSN_SAMPLES = [
    "234-56-7890",
    "345-67-8901",
    "456-78-9012",
    "567-89-0123",
    "678-90-1234",
    "112-23-3445",
    "223-34-4556",
    "334-45-5667",
]

# IRS-valid EIN prefixes.
_EIN_SAMPLES = [
    "12-3456789",
    "27-9999999",
    "33-1112222",
    "45-6789012",
    "52-1111111",
    "91-8765432",
    "84-2223333",
    "02-4567891",
    "16-1112223",
    "22-3334445",
]

# Federal Reserve Bank routings — public, real numbers, no individual link.
_ROUTING_SAMPLES = [
    "011000015",  # FRB Boston
    "021000021",  # FRB NY / Chase
    "121000358",  # FRB SF
    "031000053",  # FRB Philadelphia
    "071000013",  # FRB Chicago
]


def bookkeeping_fixtures() -> tuple[CorpusFixture, ...]:
    fixtures: list[CorpusFixture] = []

    # Bank statement headers (high-stakes for the Converter).
    for i, (acct, routing) in enumerate(zip(
        ["123456789012", "987654321098", "456789012345", "234567890123", "111222333444"],
        _ROUTING_SAMPLES,
        strict=False,
    )):
        name = _faker.name()
        text = (
            f"Statement for {name}, Account # {acct}, Routing {routing}. "
            f"Period 2026-04-01 to 2026-04-30. Opening balance $4,201.33, closing $5,187.42."
        )
        fixtures.append(
            CorpusFixture(
                id=f"bk_stmt_{i}",
                text=text,
                expected=_spans_for(
                    text,
                    [
                        ("PERSON", name),
                        ("US_BANK_ACCOUNT", acct),
                        ("US_BANK_ROUTING", routing),
                    ],
                ),
            )
        )

    # SSN-bearing taxpayer notes.
    for i, ssn in enumerate(_SSN_SAMPLES):
        name = _faker.name()
        text = f"Taxpayer {name}, SSN {ssn}, was contacted on April 12 about the 1099-NEC discrepancy."
        fixtures.append(
            CorpusFixture(
                id=f"bk_ssn_{i}",
                text=text,
                expected=_spans_for(text, [("PERSON", name), ("US_SSN", ssn)]),
            )
        )

    # EIN-bearing entity records.
    for i, ein in enumerate(_EIN_SAMPLES):
        name = f"{_faker.last_name()} Holdings LLC"
        text = f"Entity {name}, EIN {ein}, filed a Form 1065 for tax year 2025."
        fixtures.append(
            CorpusFixture(
                id=f"bk_ein_{i}",
                text=text,
                expected=_spans_for(
                    text,
                    [
                        ("BUSINESS_NAME", name),
                        ("US_EIN", ein),
                    ],
                ),
            )
        )

    # Email + phone in client correspondence.
    for i in range(10):
        name = _faker.name()
        local = (
            re.sub(r"[^a-z]", ".", name.lower()).strip(".")
            or _faker.user_name()
        )
        domain = "example.com"
        email = f"{local}@{domain}"
        # Use the reserved 555-01xx test phone range.
        last4 = f"{i:04d}"
        phone = f"(415) 555-{last4[-4:]}"
        text = f"Client contact: {name}, {email}, {phone}. Schedule the QBR."
        fixtures.append(
            CorpusFixture(
                id=f"bk_contact_{i}",
                text=text,
                expected=_spans_for(
                    text,
                    [
                        ("PERSON", name),
                        ("EMAIL_ADDRESS", email),
                        ("PHONE_NUMBER", phone),
                    ],
                ),
            )
        )

    # Combined paragraph — exercises multi-entity cross-check.
    name = _faker.name()
    ssn = _SSN_SAMPLES[0]
    ein = _EIN_SAMPLES[0]
    routing = _ROUTING_SAMPLES[0]
    text = (
        f"For 2025 returns, taxpayer {name} (SSN {ssn}) is the sole owner of "
        f"Acme Bookkeeping LLC (EIN {ein}). Operating account routes to {routing}. "
        f"Confirm DOB and email contact at admin@example.com before signoff."
    )
    fixtures.append(
        CorpusFixture(
            id="bk_combined_0",
            text=text,
            expected=_spans_for(
                text,
                [
                    ("PERSON", name),
                    ("US_SSN", ssn),
                    ("BUSINESS_NAME", "Acme Bookkeeping LLC"),
                    ("US_EIN", ein),
                    ("US_BANK_ROUTING", routing),
                    ("EMAIL_ADDRESS", "admin@example.com"),
                ],
            ),
        )
    )

    return tuple(fixtures)
